trigger:
- main       #LIST       # Runs when changes are pushed to the 'main' branch
- master
- devops

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent

steps:
- script: mvn test
  displayName: 'Unit test script for Project'
  