trigger:
- main       #LIST       # Runs when changes are pushed to the 'main' branch
- master
- devops

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent

steps:
- script: mvn package
  displayName: 'Generate build package for Project'
  env:
  MAVEN_OPTS: -DskipTests=true  # Skip tests during the build process
  